### PR TITLE
Fixed crash, Fixed FakeLag, Fixed AA Grenade predictions, Added AimBot FOV visual, Made spam use in to a keybind

### PR DESCRIPTION
**Pull request by SK0lll**
Credits for the **aimbot FOV visual** go to @ThebestkillerTBK  .
Credits for the **Fake lag fix** go to @notgoodusename  .
Fixed crash.
All you need to know is in the commits. 
So far everything worked as expected, don't forget to report bugs if found. 

Issues that can be closed:
#102

### CODE REVIEW

**Comment by linuxer9** [comment]
use spam doesn't need to be a keybind

**Comment by SK0lll** [comment]
> use spam doesn't need to be a keybind

Did you try to use it in game while tiring to open a normal door and then block it from your enemy/teammate ? 
You need to switch it off in menu and that's inconvenient.

**Comment by linuxer9** [comment]
> > use spam doesn't need to be a keybind
> 
> Did you try to use it in game while tiring to open a normal door and then block it from your enemy/teammate ? You need to switch it off in menu and that's inconvenient.

I use it, and it works fine, it opens doors if you click it once, I find it inconvenient that you have to hold two buttons for it work.
the idea of the keybind that there was some bad scripts doesn't check if you are in bomb planting area, but NEPS already checks for that, so you don't need keybind, anyway thanks for the PR.

**Comment by SK0lll** [comment]
> 

You don't have to hold two buttons at the same time, just make the keybind toggleable or on always. You basically have just more customizability, and nothing stopping you how you were using it previously.

**Pull request closed without merging**
